### PR TITLE
Fix schedule strategy, make scheduling more uniform

### PR DESCRIPTION
**Pull request by ccl0326**
as title.

### CODE REVIEW

**Review by supermeng — APPROVED** [review]

**Comment by fossilet** [comment]
The Travis CI status is not updated automatically. I have contacted GitHub help.

**Comment by fossilet** [comment]
I also contacted Travis CI. They are seeing some authentication errors for this issue as well as [this one](https://travis-ci.org/laincloud/console/builds/262491502), and they are investigating the problem.

**Comment by fossilet** [comment]
@ccl0326 thank you.

**Comment by fossilet** [comment]
I manually restarted the build and triggered a status update.

**Pull request merged**
